"use strict"

/*
 * NESTA AULA VAMOS FALAR SOBRE OPERADORES ARITMÉTICOS NO JS
 * TIPOS DE OPERADORES
 * + SOMA
 * - SUBTRAÇÃO
 * | * MULTIPLICAÇÃO
 * | ** EXPONENCIAÇÃO
 * / DIVISÃO
 * % RESTO DA DIVISÃO
 * ++ INCREMENTO
 * -- DECREMENTO
*/

